#!/bin/sh

CONTAINER_N=nginx
CONTAINER_S=sass

SASS_BASE=/var/sass
SASS_DST=${SASS_BASE}/assets/css/style.css

docker exec ${CONTAINER_S} rm -rf ${SASS_DST}
docker rm -f ${CONTAINER_S}
docker rm -f ${CONTAINER_N}
