#!/bin/sh

VOL=$(cd $(dirname $0); pwd):/usr/share/nginx/html:ro
CONTAINER=`docker run -d -p 4000:80 -v ${VOL} nginx:alpine`
IP=`docker-machine ip docker`
printf "Please open via browser: \e[1;4mhttp://${IP}:4000\e[m\n"
read -p "Press any key to shutdown server."
docker rm -f ${CONTAINER}
