#!/bin/sh

CONTAINER_N=nginx
CONTAINER_S=sass

SASS_BASE=/var/sass
SASS_SRC=${SASS_BASE}/assets/sass/style.scss
SASS_DST=${SASS_BASE}/assets/css/style.css

PWD=$(cd $(dirname $0); pwd)
VOL_S=${PWD}:${SASS_BASE}
VOL_N=${PWD}:/usr/share/nginx/html:ro
CMD_S=sass --watch ${SASS_SRC}:${SASS_DST}

#docker run --rm -v ${VOL_S} alpine:edge ls
docker run -d -v ${VOL_S} --name ${CONTAINER_S} danmaq/ruby-sass ${CMD_S}
docker run -d -p 4000:80 -v ${VOL_N} --name ${CONTAINER_N} nginx:alpine
